### ISSUE TITLE
Date of started game thread is 24hrs ahead

### ISSUE THREAD

**Issue by tashavanes** [shayypy/puckway#1]
we are having Puckway start PWHL game threads in our server, so far every game thread is 1 day ahead (for example today's game was posted as Saturday, Dec 7th). Everything else is correct. I can just go change the title to today's date, but is this a server configuration issue or a bot issue? Thank you for any assistance.

**Comment by shayypy** [comment]
This is fixed in a recent commit but it's not yet published. Will close this issue when that's live!

**Comment by tashavanes** [comment]
much appreciated!
